### ISSUE TITLE
One less abusive IP, it was just shutdown

### ISSUE THREAD

**Issue by solbu** [ShadowWhisperer/IPs#3]
Hi.
Not sure if this makes any difference, but I'm reporting it here anyway.

I am _one_ of the sysadmins of the network at the IP 89.11.150.231 which is in this Hackers list.
The network is owned by a friend of mine, which have a Debian based homelab in his apartment.

Earlier today he complained on a Linux IRC channel that several services and sites blocked his IP, and he could not figure out why.
After a short investigation by me, it was determined that a virtual machine had an unsecured selfmade web application, and someone managed to use it to deploy an SSH Bot malware.

The server is now secured, the malware deleted and the VM shutdown.
After shutting it down, the abuseIPDB site no longer reports any atcivity from this IP.
It was also decided that this application will be locked behind a htaccess login, and will Not be available on the internet
as he only really need it at home..

Just wanted to let you know, as when I googled his IP it showed up in this github repo.

Greetings from a helpfull sysadmin.

**Comment by solbu** [comment]
Oh, and the VM will be deleted and a new one created from scratch, as a precaution. :-)

**Comment by ShadowWhisperer** [comment]
Looks like your friend's IP has been reported over 3,000 times. I'm afraid removing it from my list won't have much of an effect. Unless he has a static IP, best bet would be to request a new IP, from his ISP. 

https://www.abuseipdb.com/check/89.11.150.231
https://www.dshield.org/ipdetails.html?ip=89.11.150.231&96
https://otx.alienvault.com/indicator/ip/89.11.150.231
https://www.malwareurl.com/listing.php?domain=89.11.150.231
https://www.virustotal.com/gui/ip-address/89.11.150.231/detection

https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
https://liquidbinary.com/blackIPs.txt
https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-ip-addresses.list


**Ports Open** - Current
```
22     SSH
80     Apache
113    Ident
443    Apache
32400  Plex
```

**Comment by solbu** [comment]
Thank you for the links.

Yes, it is a static IP, which makes it easier to determine if the VM was the only infected system.
And the open ports are known and have been deliberatly open for many years. :-)

**Comment by ShadowWhisperer** [comment]
**abuseipdb** shows it is still actively sending out attacks

**Comment by solbu** [comment]
Yes, but in the entries that include the timestamp, nothing is logged since october 26.

The anonymous repport from 11 hours ago are timestamped october 23 and was reported to the abuseipdb _6 days Later_

The exception is the indian report by Parth Maniar, which is ahead of us by 3 hours and 30 minutes.
Our server were UTC+2 (Europe just left summer time some 4 hours ago), and his server is UTC+5.30, and the VM was shutdown and removed from the internet at 23:57 european time (11:57 pm) or something like that, on october 26.

The fail2ban module used for reporting this was updated at one point to remove a bug which repported already reported IPs if the fail2ban service was restarted.

So those are delayed repports.
